
const randomTextDataFile = {
        0: "Kawabunga!",
        1: "Andale",
        3: "That's what she said",
        4: "That's allright mama",
        5: "You shall not pass!",
        6: "Aliens",
        7: "My best friend",
        8: "Keep calm and",
        9: "OMG",
        10: "WTF?",
        11: "LOL",
        12: "YOLO",
        13: "Pink Floyd",
        14: "Average",
        15: "People",
        16: "Frankly, my dear",
        17: "Toto, I've a feeling we're not in Kansas anymore",
        18: "Go ahead",
        19: "Make my day",
        20: "May the force be with you",
        21: "Fastern your seatbelts",
        22: "It's going to be a bumpy night",
        23: "I love the smell",
        24: "Napalm in the morning",
        25: "Sitting in the dock of the bay",
        26: "Love means",
        27: "Louis",
        28: "I think this is the beginning of a beautiful friendship",
        29: "Bond, James Bond",
        30: "Beat it",
        31: "Monday",
        32: "Tuesday",
        33: "Friday",
        34: "Saturday",
        35: "Sunday",
        36: "Hello",
        37: "Hasta la vista baby",
        38: "You're gonna need a bigger boat",
        39: "I'll be back",
        40: "I see",
        41: "Stella!",
        42: "It's alive!",
        43: "Huston",
        44: "You had me at 'hello'",
        45: "As God is my witness",
        46: "You're trying to seduce me",
        47: "Elementary",
        48: "My dear Watson",
        49: "It's Chinatown!",
        50: "Carpe diem",
        51: "Seize the day",
        52: "With a little help from my friends",
        53: "Excuse me",
        54: "Sir",
        55: "Madam",
        56: "I kissed a girl",
        57: "I like",
        58: "Male privilege is a myth",
        59: "Change my mind",
        60: "Well",
        61: "That escalated quickly",
        62: "Be like Bill",
        63: "That'd be great",
        64: "Ain't nobody got time for that",




    }

export default randomTextDataFile